plugins {
    id 'java'
    id("io.qameta.allure") version "4.1.0"
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation group: 'org.assertj', name: 'assertj-core', version: '3.27.7'
    compileOnly group: 'org.projectlombok', name: 'lombok', version: '1.18.46'
    testCompileOnly group: 'org.projectlombok', name: 'lombok', version: '1.18.46'
    annotationProcessor group: 'org.projectlombok', name: 'lombok', version: '1.18.46'
    testAnnotationProcessor group: 'org.projectlombok', name: 'lombok', version: '1.18.46'
    testImplementation group: 'tools.jackson.core', name: 'jackson-databind', version: '3.2.1'
    testImplementation group: 'com.fasterxml.jackson.datatype', name: 'jackson-datatype-jsr310', version: '2.22.1'
    testImplementation group: 'org.aeonbits.owner', name: 'owner', version: '1.0.12'
    testImplementation group: 'net.datafaker', name: 'datafaker', version: '2.7.0'
    testImplementation group: 'org.postgresql', name: 'postgresql', version: '42.7.13'
    testImplementation group: 'io.rest-assured', name: 'rest-assured', version: '6.0.1'
    testImplementation group: 'io.qameta.allure', name: 'allure-rest-assured', version: '2.35.4'
}

compileJava {
    options.encoding = 'UTF-8'
}

compileTestJava {
    options.encoding = 'UTF-8'
}


test {
    useJUnitPlatform()
}